@startuml
class User {
-string name;
-string password;
-int coins=20;

-list cardInventory;
-list deck;
+void login(string password);
+void getDeck();
+void buyCards();
}

enum Element{
Fire,
Water,
Normal
}

abstract class Card
{

-int tier;
-string name;
-int baseDamage;
-Element element;

+void describe();

}

class Manager
{
    +void trade(User player1, User player2);
    +void battle(User player1, User player2);
}

class Main()
{
    void resolveElement();
    void resolveMonsterType();
    void fight();
}


enum MonsterType
{
    Goblin,
        Wizard,
        Ork,
        Knight,
        Kraken,
        Elf,
        Dragon
}

class MonsterCard
{
+MonsterType type;
+override void describe()
}
class SpellCard
{
+override void describe()
}

Card <|-- "extends" MonsterCard
Card <|-- "extends" SpellCard

User "owns multiple" *-- Card
Card "has one" *-- Element

MonsterCard "has one" *-- MonsterType
User "interacts with other users through" --* Manager

@enduml